# Generated by Django 3.2.5 on 2022-10-26 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_record_voice_record'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='meaning',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='record',
            name='meaning_in_english',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='record',
            name='meaning_in_swahili',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='record',
            name='voice_record_use_case',
            field=models.FileField(blank=True, null=True, upload_to='use_cases'),
        ),
        migrations.AddField(
            model_name='record',
            name='word',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='record',
            name='voice_record',
            field=models.FileField(blank=True, null=True, upload_to='records'),
        ),
    ]
